spring:
  profiles:
    active: production

  devtools:
    restart:
      enabled: false
      
  jpa:
    hibernate:
      use-new-id-generator-mappings: true

server:
  session:
    persistent: true
    tracking-modes: "cookie"

security:
  basic:
    enabled: false

management:
  add-application-context-header: false
